<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.github.andrestubbe</groupId>
    <artifactId>fastbot-demo</artifactId>
    <version>0.1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.github.andrestubbe</groupId>
            <artifactId>fastbot</artifactId>
            <version>0.1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.github.andrestubbe</groupId>
            <artifactId>FastTerminal</artifactId>
            <version>0.1.3</version>
        </dependency>
        <dependency>
            <groupId>com.github.andrestubbe</groupId>
            <artifactId>FastTUI</artifactId>
            <version>0.1.1</version>
        </dependency>
        <dependency>
            <groupId>com.github.andrestubbe</groupId>
            <artifactId>FastKeyboard</artifactId>
            <version>0.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.andrestubbe</groupId>
            <artifactId>FastSoftware3D</artifactId>
            <version>0.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.andrestubbe</groupId>
            <artifactId>FastTerminal3D</artifactId>
            <version>0.1.1</version>
        </dependency>
        <dependency>
            <groupId>com.github.andrestubbe</groupId>
            <artifactId>FastTTS</artifactId>
            <version>0.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.andrestubbe</groupId>
            <artifactId>FastAudioPlayer</artifactId>
            <version>0.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.andrestubbe</groupId>
            <artifactId>FastAudioProcess</artifactId>
            <version>0.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.andrestubbe</groupId>
            <artifactId>FastAnimation</artifactId>
            <version>0.1.0</version>
        </dependency>
    </dependencies>
</project>
